### ISSUE TITLE
Not working with OC 0.9.6

### ISSUE THREAD

**Issue by TTP1106** [knuxyl/lattepandalpha_bigsur#1]
I tried to copy your Repo to a new USB. Stick with Big Sur and actual OpenCore release but it failed.
There are some drivers mismatch. When I copy it from actual release I get the error "BEP: Invalid revision 5 (!= 1) in loaded driver. 
Halting on critical error.

Would be nice to update your repo because it´s 2 years old.

**Comment by knuxyl** [comment]
I took some components off my board last year so I have no way to test it anymore. If you follow the opencore guide and something doesn't work you can use this repo as a reference. I won't be updating this.
